company.com/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Users;
use App\Http\Controllers\Marketing;
use App\Http\Controllers\HumanResources;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
Route::get('/dashboard1', function () {
    return view('dashboard1');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/users', [Users::class, 'getUsers'])->name('getUsers');
    Route::post('/addUsers', [Users::class, 'addUsers'])->name('adduser');


    Route::get('/marketing/customers', [Marketing::class, 'customers'])->name('marketing.customers');
    Route::post('/marketing/addcustomer', [Marketing::class, 'addCustomer'])->name('marketing.addcustomer');

    Route::get('/marketing/category', [Marketing::class, 'category'])->name('marketing.category');
    Route::post('/marketing/addcategory', [Marketing::class, 'addCategory'])->name('marketing.addcategory');

    Route::get('/marketing/project', [Marketing::class, 'projects'])->name('marketing.projects');
    Route::post('/marketing/addproject', [Marketing::class, 'addProject'])->name('marketing.addproject');


    Route::get('/marketing/services', [Marketing::class, 'services'])->name('marketing.services');
    Route::post('/marketing/addservices', [Marketing::class, 'addServices'])->name('marketing.addservices');

    Route::get('/marketing/locations', [Marketing::class, 'locations'])->name('marketing.locations');
    Route::post('/marketing/addlocations', [Marketing::class, 'addLocations'])->name('marketing.addlocations');

    Route::get('/marketing/paymentmethods', [Marketing::class, 'paymentMethods'])->name('marketing.paymentmethods');
    Route::post('/marketing/addpaymentmethod', [Marketing::class, 'addPaymentMethod'])->name('marketing.addpaymentmethod');

    Route::get('/marketing/jobtitles', [Marketing::class, 'jobTitles'])->name('marketing.jobtitles');
    Route::post('/marketing/addjobtitles', [Marketing::class, 'addJobTitles'])->name('marketing.addjobtitles');

    Route::post('/delete', [Marketing::class, 'delete'])->name('delete');
    Route::get('/marketing/edit/{action?}/{id?}', [Marketing::class, 'edit'])->name('marketing.edit');
    Route::post('/marketing/edit/update/{action?}/{id?}', [Marketing::class, 'update'])->name('marketing.update');


    Route::get('/marketing/payments', [Marketing::class, 'payments'])->name('marketing.payments');
    Route::get('/marketing/payments/{id}', [Marketing::class, 'paymentsEdit'])->name('marketing.payments.edit');
    Route::post('/marketing/updatepayments', [Marketing::class, 'paymentsUpdate'])->name('marketing.payments.update');
    Route::get('/marketing/addpayments', [Marketing::class, 'create'])->name('marketing.addpayments');
    Route::post('/marketing/addpayments', [Marketing::class, 'store'])->name('marketing.savepayment');
    Route::post('/marketing/lock', [Marketing::class, 'lock'])->name('marketing.lock');
    Route::post('/marketing/lockall', [Marketing::class, 'lockAll'])->name('marketing.lockall');
    Route::post('/marketing/lockfromto', [Marketing::class, 'lockFromTo'])->name('marketing.lockfromto');
    Route::get('/marketing/getCustomerIdbyConctact', [Marketing::class, 'getCustomerIdbyConctact'])->name('marketing.getCustomerIdbyConctact');

    Route::get('/marketing/paymentbyrefno/{id?}', [Marketing::class, 'paymentByRefNo'])->name('marketing.paymentbyrefno');
    Route::get('/marketing/search', [Marketing::class, 'searchPayments'])->name('marketing.payments.search');

    ///Hr
    Route::get('/hr/jobtitles', [HumanResources::class, 'jobTitles'])->name('hr.jobtitles');
    Route::post('/hr/addjobtitles', [HumanResources::class, 'addJobTitles'])->name('hr.addjobtitles');

    Route::get('/hr/projects', [HumanResources::class, 'projects'])->name('hr.projects');
    Route::post('/hr/addprojects', [HumanResources::class, 'addProjects'])->name('hr.addprojects');


    Route::get('/hr/status', [HumanResources::class, 'status'])->name('hr.status');
    Route::post('/hr/addstatus', [HumanResources::class, 'addStatus'])->name('hr.addstatus');

    Route::post('/hr/delete', [HumanResources::class, 'delete'])->name('hr.delete');

    Route::get('/hr/edit/{action?}/{id?}', [HumanResources::class, 'edit'])->name('hr.edit');
    Route::post('/hr/edit/update/{action?}/{id?}', [HumanResources::class, 'update'])->name('hr.update');

    Route::get('/hr/addemploy', [HumanResources::class, 'addEmploy'])->name('hr.addemploy');
    Route::get('/hr/employ', [HumanResources::class, 'employ'])->name('hr.employ');
    Route::post('/hr/employeesave', [HumanResources::class, 'employeeSave'])->name('hr.saveemployee');
    Route::post('/hr/employeeupdate', [HumanResources::class, 'employeeUpdate'])->name('hr.updateemployee');

    Route::post('/hr/lock', [HumanResources::class, 'lock'])->name('hr.lock');
    Route::post('/hr/lockall', [HumanResources::class, 'lockAll'])->name('hr.lockall');

    Route::get('/hr/employ/edit/{action?}/{id?}', [HumanResources::class, 'employEdit'])->name('hr.employ.edit');
    Route::post('/hr/employ/edit/update/{action?}/{id?}', [HumanResources::class, 'employUpdate'])->name('hr.employ.update');

    Route::get('/hr/search', [HumanResources::class, 'searchEmploy'])->name('hr.employ.search');
    Route::post('/hr/send', [HumanResources::class, 'sendEmploy'])->name('hr.employ.send');
    Route::post('/hr/undosend', [HumanResources::class, 'undoSend'])->name('hr.undosend');
    Route::post('/hr/sendall', [HumanResources::class, 'sendAllEmploy'])->name('hr.employ.sendall');
    Route::get('/hr/attendances', [HumanResources::class, 'attendances'])->name('hr.attendances');


    Route::get('/attendance', [HumanResources::class, 'attendance'])->name('attendance');
    Route::post('/saveattendance', [HumanResources::class, 'saveAttendance'])->name('saveattendance');

    Route::get('/resetpassword', [Users::class, 'resetPassword'])->name('resetpassword');
    Route::POST('/updatepassword', [Users::class, 'updatepassword'])->name('updatepassword');

    Route::get('/hrattendance', [HumanResources::class, 'hrattendance'])->name('hrattendance');
    Route::get('/getcustomernamebyprojectid', [HumanResources::class, 'getCustomerbyProjectId'])->name('getcustomernamebyprojectid');

    Route::get('/download', function (Request $request){
        $filename = $request->filename;
        return response()->download(storage_path('/app/public/'. $filename));

        $file=Storage::disk('public')->get($filename);

        return (new Response($file, 200))
            ->header('Content-Type', 'image/jpeg');
    })->name('download');
});

Route::get('/cache', function(){
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
});

Route::get('/time', function(){
    echo date('d.m.Y H:i:s');
});

Route::get('/dumpdb', function(){
    Spatie\DbDumper\Databases\MySql::create()
        ->setDbName('company')
        ->setUserName('root')
        ->setPassword('')
        ->dumpToFile('dump.sql');
});

Route::get('/backupdb', [Users::class, 'backupDB'])->name('backupdb');

company.com/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

company.com/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

company.com/resources/views/dashboard.blade.php
@extends('index')

@section('content')
    <div class="page-wrapper" style="display: block;">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1">Welcome {{Auth::user()->name}}!</h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <li class="breadcrumb-item">Logged in to <b>AQG</b>
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-5 align-self-center">
                    <!-- <div class="customize-input float-right">
                        <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                            <option selected>
                            November&nbsp;
                            <script>document.write(new Date().getDate());</script>,
                            &nbsp;
                            <script>document.write(new Date().getFullYear());</script></option>
                        </select>
                    </div> -->


                    <div class="customize-input float-right">
                        <h4 class=" custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                            Date:
                            {{date('d/m/Y @ H:i')}}
                        </h4>
                    </div>


                </div>
            </div>
            @if(Auth::user()->title == 0 && false)
            <div class="card-group mt-5">
                <div class="card border-right">
                    <div class="card-body">
                        <div class="d-flex d-lg-flex d-md-block align-items-center">
                            <div>
                                <h2 class="text-dark mb-1 w-100 text-truncate font-weight-medium"><sup class="set-doller">QR</sup>18,306</h2>
                                <h6 class="text-dark font-weight-normal mb-0 w-100 text-truncate">Total Income
                                </h6>
                            </div>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-dark"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-pocket"><path d="M4 3h16a2 2 0 0 1 2 2v6a10 10 0 0 1-10 10A10 10 0 0 1 2 11V5a2 2 0 0 1 2-2z"></path><polyline points="8 10 12 14 16 10"></polyline></svg></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card border-right">
                    <div class="card-body">
                        <div class="d-flex d-lg-flex d-md-block align-items-center">
                            <div>
                                <h2 class="text-dark mb-1 w-100 text-truncate font-weight-medium">306</h2>
                                <h6 class="text-dark font-weight-normal mb-0 w-100 text-truncate">Total Customers
                                </h6>
                            </div>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-dark"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card border-right">
                    <div class="card-body">
                        <div class="d-flex d-lg-flex d-md-block align-items-center">
                            <div>
                                <h2 class="text-dark mb-1 w-100 text-truncate font-weight-medium">125</h2>
                                <h6 class="text-dark font-weight-normal mb-0 w-100 text-truncate">Total Employees
                                </h6>
                            </div>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-dark"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-check"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><polyline points="17 11 19 13 23 9"></polyline></svg></span>
                            </div>
                        </div>
                    </div>
                </div>
               {{-- <div class="card border-right">
                    <div class="card-body">
                        <div class="d-flex d-lg-flex d-md-block align-items-center">
                            <div>
                                <h2 class="text-dark mb-1 w-100 text-truncate font-weight-medium">73</h2>
                                <h6 class="text-dark font-weight-normal mb-0 w-100 text-truncate">Total Projects
                                </h6>
                            </div>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-dark"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-plus"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="12" y1="18" x2="12" y2="12"></line><line x1="9" y1="15" x2="15" y2="15"></line></svg></span>
                            </div>
                        </div>
                    </div>
                </div>--}}
            </div>

           @endif


        </div>
        <div class="container-fluid">
        </div>
    </div>
@stop

company.com/resources/views/dashboard0.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

company.com/resources/views/home.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head><title>@yield('title','AQG | Abraj Qatar Group')</title>

    @includeIf('include.styles')
</head>

<body>
<div>
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper" style="display: contents;">

        <div class="page-breadcrumb" >

        </div>
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- *************************************************************** -->
            <!-- Start First Cards -->
            <!-- *************************************************************** -->


            <!-- *************************************************************** -->
            <!-- End First Cards -->
            <!-- *************************************************************** -->
            <!-- *************************************************************** -->
            <!-- Start Latest Games Section -->
            <!-- *************************************************************** -->
            <div class="row ">
                <!-- stats start -->
                <div class="col-12">
                    {{--<div class="col-3 text-center" style="max-width: 20%;">

                        <div class="customize-input">
                            <h4 class=" custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                                {{date('d/m/Y @ H:i')}}
                            </h4>

                        </div>
                    </div>--}}




                    <div class="jumbotron jumbotron-fluid" style="background-color: inherit;">
                        <div class="text-center">
                            <h1 class="display-3 text-dark">WELCOME TO ABRAJ QATAR GROUP</h1>
                        </div>
                    </div>





                </div>
                <!-- stats end -->
            </div>

            <br>
            <!-- Row -->
            <div class="row">
                <div class="col-12">
                    <!-- Row -->
                    <div class="row">
                        <!-- column -->
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-2 col-md-6">
                            <!-- Card -->
                            <div class="card no-shadow  text-center">
                                <a href="{{route('login')}}"><img src="{{asset('assets/dist/imgs/abraj.jpg')}}" alt="image" class="card-img-top img-fluid rounded-circle img-shadow"
                                                              width="200"></a>
                                <div class="card-body">
                                    <a href="{{route('login')}}"><h3 class="card-title text-maroon">A.Q.G</h3></a>
                                    <!--<a href="javascript:void(0)" class="btn btn-rounded btn-maroon mt-2">Visit&emsp;<i class="fas fa-angle-right"></i></a>-->
                                </div>
                            </div>
                            <!-- Card -->
                        </div>
                        <!-- column -->
                        <!-- column -->
                        <div class="col-lg-2 col-md-6">
                            <!-- Card -->
                            <div class="card no-shadow  text-center">
                                <a href="chem_dry_login.html"><img src="{{asset('assets/dist/imgs/chem.jpg')}}" alt="image" class="card-img-top img-fluid rounded-circle img-shadow"
                                                                   width="200"></a>
                                <div class="card-body">
                                    <a href="chem_dry_login.html"><h3 class="card-title">CHEM-DRY QATAR</h3></a>
                                    <!--<a href="javascript:void(0)" class="btn btn-rounded btn-maroon mt-2">Visit&emsp;<i class="fas fa-angle-right"></i></a>-->
                                </div>
                            </div>
                            <!-- Card -->
                        </div>
                        <!-- column -->
                        <!-- column -->
                        <div class="col-lg-2 col-md-6">
                            <!-- Card -->
                            <div class="card no-shadow text-center">
                                <a href="royal_valet_login.html"><img src="{{asset('assets/dist/imgs/royal.jpg')}}" alt="image" class="card-img-top img-fluid rounded-circle img-shadow"
                                                                      width="200"></a>
                                <div class="card-body">
                                    <a href="royal_valet_login.html"><h3 class="card-title">ROYAL VALET</h3></a>
                                    <!--<a href="javascript:void(0)" class="btn btn-rounded btn-maroon mt-2">Visit&emsp;<i class="fas fa-angle-right"></i></a>-->
                                </div>
                            </div>
                            <!-- Card -->
                        </div>
                        <!-- column -->
                        <!-- column -->
                        <div class="col-lg-2 col-md-6 img-fluid">
                            <!-- Card -->
                            <div class="card no-shadow text-center">
                                <a href="spider_cleaning_login.html"><img src="{{asset('assets/dist/imgs/spider.jpg')}}" alt="image" class="card-img-top img-fluid rounded-circle img-shadow"
                                                                          width="200"></a>
                                <div class="card-body">
                                    <a href="spider_cleaning_login.html"><h3 class="card-title text-spider">SPIDER CLEANING</h3></a>
                                    <!--<a href="javascript:void(0)" class="btn btn-rounded btn-maroon mt-2">Visit&emsp;<i class="fas fa-angle-right"></i></a>-->
                                </div>
                            </div>
                            <!-- Card -->
                        </div>
                        <!-- column -->
                        <div class="col-lg-2">
                        </div>
                    </div>
                    <!-- Row -->
                </div>
            </div>
            <!-- End Row -->
            <!-- *************************************************************** -->
            <!-- End Latest Games Section -->
            <!-- *************************************************************** -->
            <!-- *************************************************************** -->
            <!-- Start Popular/Categories Games Section -->
            <!-- *************************************************************** -->

            <!-- *************************************************************** -->
            <!-- End Popular/Categories Games Section -->
            <!-- *************************************************************** -->
            <!-- *************************************************************** -->
            <!-- Start Similar Games Section -->
            <!-- *************************************************************** -->

            <!-- *************************************************************** -->
            <!-- End Similar Games Section -->
            <!-- *************************************************************** -->


        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
    @includeIf('include.footer')
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
</div>

</body>
@includeIf('include.scripts')
</html>

company.com/resources/views/index.blade.php
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <meta property="og:type" content="website"/>
    {{--    <meta property="og:image" content="http://my.site.com/images/thumb.png" />--}}


    <title>@yield('title','AQG | Abraj Qatar Group')</title>
    @includeIf('include.styles')
</head>
<body class="hold-transition sidebar-mini">

<div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
    @includeIf('include.navbar')
    @includeIf('include.sidebar')
    @yield('content')
    @includeIf('include.footer')
</div>
@includeIf('include.scripts')
@includeIf('include.messagemodal')
</body>
</html>

company.com/resources/views/main.blade.php
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <meta property="og:type" content="website"/>
    {{--    <meta property="og:image" content="http://my.site.com/images/thumb.png" />--}}

    <title>@yield('title','AQG | Abraj Qatar Group')</title>
    @includeIf('include.styles')
</head>
<body class="hold-transition sidebar-mini">

<div class="main-wrapper">
    <div class="auth-wrapper d-flex no-block justify-content-center align-items-center position-relative"
    >
    @yield('content')
    </div>
    @includeIf('include.footer')
</div>
@includeIf('include.scripts')
@includeIf('include.messagemodal')
</body>
</html>

company.com/resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

company.com/resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>